### ISSUE TITLE
Example aiida input file?

### ISSUE THREAD

**Issue by RKBK** [cp2k/aiida-cp2k#1]
Hi,

To clarify how to use this plugin, would it be possible for you to upload a simple aiida input example?

**Comment by oschuett** [comment]
Hi,
you can have a look at https://github.com/cp2k/aiida-cp2k/blob/master/test.py . It contains three examples.
-Ole

**Comment by RKBK** [comment]
Perfect, that's just what I needed. 

In particular, I was confused about how to generate e.g. 

```
&DIAGONALIZATION ON
```

but as is shown in the test, it is

```python
'DIAGONALIZATION': {
'_': 'ON'}
```
