### ISSUE TITLE
Is it Possible to Create a New Type of Data for cp2k in AiiDA

### ISSUE THREAD

**Issue by Cloudac7** [cp2k/aiida-cp2k#13]
As is descried in the release note of AiiDA, after the version 0.11.0, plugins can now add custom commands to `verdi data`. So is it a choice for our cp2k plugin to store the `BASIS_MOLOPT`
and `GTH_POTENTIAL` files as data in DB, and then it will be easier for us to import them?

**Comment by oschuett** [comment]
The aiida-cp2k plugin treads data files (basis sets, pseudo potentials, VdW, etc.) a bit different than the rest of AiiDA.

The CP2K releases comes with a [data directory](https://github.com/cp2k/cp2k/tree/master/cp2k/data) that contains all popular parameter sets. Therefore, these files a simply considered part of the code - no need to upload them to the AiiDA database.

You can simply reference a file via it's basename in your input, e.g.:
```
'BASIS_SET_FILE_NAME': 'BASIS_MOLOPT'
```
CP2K will then pickup the correct file from it's data directory.
